# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55a0ca348abb20245d627b19348db6b1675165d6da8b04a1282beb0ab8e8dc7dd9a2f45d83a99b1469e6420910da973d6e9b498bc5a0a6337b100dc4a58dfaae

test:
  secret_key_base: 1f02236bc39df20b1aa5b979eeaa78138990f32b98ad57917e1276aecc37cd33f1bd242e6508afbec1ac0cc0de1e39bff80666475f17d4b674a8c2985309dc66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
